<a href="https://colab.research.google.com/github/AsserAttiaHue20/Sales_Analysis_Dashboard/blob/main/Global_Superstore_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [82]:
data=pd.read_csv('/content/Global_Superstore_Clean.csv')

In [83]:
data.shape

(51290, 29)

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   row_id             51290 non-null  int64
 1   order_id           51290 non-null  object
 2   order_date         51290 non-null  object
 3   ship_date          51290 non-null  object
 4   ship_mode          51290 non-null  object
 5   customer_id        51290 non-null  object
 6   customer_name      51290 non-null  object
 7   segment            51290 non-null  object
 8   city               51290 non-null  object
 9   state              51290 non-null  object
 10  country            51290 non-null  object
 11  market             51290 non-null  object
 12  region             51290 non-null  object
 13  product_id         51290 non-null  object
 14  category           51290 non-null  object
 15  sub-category       51290 non-null  object
 16  product_name       51290 non-null  object
 17  sales              51290 non-null  float64
 18  quantity           51290 non-null  int64
 19  discount           51290 non-null  float64
 20  profit             51290 non-null  float64
 21  shipping_cost      51290 non-null  float64
 22  order_priority     51290 non-null  object
 23  shipping_duration  51290 non-null  int64
 24  profit_margin      51290 non-null  float64
 25  order_year         51290 non-null  int64
 26  is_profitable      51290 non-null  bool
 27  order_month        51290 non-null  object
 28  discount_level     51290 non-null  object
dtypes: bool(1), float64(5), int64(4), object(19)
memory usage: 11.0+ MB

In [85]:
data.head(10)

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,discount,profit,shipping_cost,order_priority,shipping_duration,profit_margin,order_year,is_profitable,order_month,discount_level
0,11731,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,Stockholm,...,0.5,-26.055,4.82,High,4,-0.580742,2011,False,January,Medium
1,22255,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,0.1,37.770,4.70,Medium,7,0.332278,2011,True,January,Low
2,48883,HU-2011-1220,2011-01-01,2011-01-05,Second Class,AT-735,Annie Thurman,Consumer,Budapest,Budapest,...,0.0,29.640,8.17,High,4,0.448276,2011,True,January,No Discount
3,22254,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,0.1,15.342,1.80,Medium,7,0.277723,2011,True,January,Low
4,42433,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,Constantine,...,0.0,106.140,35.46,Medium,5,0.259956,2011,True,January,No Discount
5,22253,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,0.1,36.036,9.72,Medium,7,0.299387,2011,True,January,Low
6,22618,IN-2013-47960,2013-01-01,2013-01-06,Standard Class,JE-15715,Joe Elijah,Consumer,Tianjin,Tianjin,...,0.0,203.700,155.15,Medium,5,0.149969,2013,True,January,No Discount
7,18034,ES-2013-5782657,2013-01-01,2013-01-07,Standard Class,CC-12220,Chris Cortes,Consumer,Melilla,Melilla,...,0.0,23.820,5.23,Medium,6,0.239445,2013,True,January,No Discount
8,22617,IN-2013-47960,2013-01-01,2013-01-06,Standard Class,JE-15715,Joe Elijah,Consumer,Tianjin,Tianjin,...,0.0,340.410,90.86,Medium,5,0.249923,2013,True,January,No Discount
9,22267,ID-2013-37383,2013-01-01,2013-01-04,First Class,MY-18295,Muhammed Yedwab,Corporate,Albury,New South Wales,...,0.1,18.948,12.79,Medium,3,0.221801,2013,True,January,Low

In [86]:
data["order_date"] = pd.to_datetime(data["order_date"])
data["ship_date"] = pd.to_datetime(data["ship_date"])

In [87]:
data["order_year"] = data["order_date"].dt.year
data["order_month"] = data["order_date"].dt.month
data["order_day"] = data["order_date"].dt.day
data["order_dayofweek"] = data["order_date"].dt.dayofweek

In [88]:
y = data["shipping_duration"]

In [89]:
X = data.drop(columns=[
    "shipping_duration",
    "ship_date",
    "order_date"
])

In [90]:
numeric_features = X.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_features = X.select_dtypes(
    include=["object"]
).columns

In [99]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [100]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [101]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['row_id', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost',
       'profit_margin'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['order_id', 'ship_mode', 'customer_id', 'customer_name', 'segment',
       'city', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub-category', 'product_name', 'order_priority',
       'discount_level'],
      dtype='object'))])),
                ('regressor', LinearRegression())])

In [102]:
y_pred = model.predict(X_test)

In [103]:
y_pred

array([4.98134567, 2.73477982, 1.99168361, ..., 1.91106456, 3.55854317,
       5.11759764])

In [104]:
y_test

49728    6
45547    3
15664    2
40561    7
49426    4
        ..
10271    5
43411    0
49462    1
30658    5
34372    5
Name: shipping_duration, Length: 10258, dtype: int64

In [105]:
mae = mean_absolute_error(y_test, y_pred)

rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5

r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 0.6941596948974076
RMSE: 0.8659639437679251
R²: 0.7516538041610941

In [106]:
print(data.columns.tolist())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'city', 'state', 'country', 'market', 'region', 'product_id', 'category', 'sub-category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_cost', 'order_priority', 'shipping_duration', 'profit_margin', 'order_year', 'is_profitable', 'order_month', 'discount_level', 'order_day', 'order_dayofweek']

In [107]:
data

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,city,state,...,shipping_cost,order_priority,shipping_duration,profit_margin,order_year,is_profitable,order_month,discount_level,order_day,order_dayofweek
0,11731,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,Stockholm,...,4.82,High,4,-0.580742,2011,False,1,Medium,1,5
1,22255,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,4.70,Medium,7,0.332278,2011,True,1,Low,1,5
2,48883,HU-2011-1220,2011-01-01,2011-01-05,Second Class,AT-735,Annie Thurman,Consumer,Budapest,Budapest,...,8.17,High,4,0.448276,2011,True,1,No Discount,1,5
3,22254,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,New South Wales,...,1.80,Medium,7,0.277723,2011,True,1,Low,1,5
4,42433,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,Constantine,...,35.46,Medium,5,0.259956,2011,True,1,No Discount,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51285,1784,MX-2014-116267,2014-12-31,2015-01-03,Second Class,EB-13975,Erica Bern,Corporate,São Paulo,São Paulo,...,4.16,High,3,0.329204,2014,True,12,No Discount,31,2
51286,23681,IN-2014-75603,2014-12-31,2015-01-05,Second Class,BS-11365,Bill Shonely,Corporate,Vijayawada,Andhra Pradesh,...,4.12,Medium,5,0.419896,2014,True,12,No Discount,31,2
51287,27701,IN-2014-23754,2014-12-31,2015-01-07,Standard Class,KM-16225,Kalyca Meade,Corporate,Shantou,Guangdong,...,4.06,Medium,7,0.368304,2014,True,12,No Discount,31,2
51288,32203,CA-2014-143259,2014-12-31,2015-01-04,Standard Class,PO-18865,Patrick O'Donnell,Consumer,New York City,New York,...,38.27,High,4,0.037500,2014,True,12,Low,31,2
51289,32204,CA-2014-143259,2014-12-31,2015-01-04,Standard Class,PO-18865,Patrick O'Donnell,Consumer,New York City,New York,...,9.67,High,4,0.030000,2014,True,12,No Discount,31,2